config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'pages#about', as: :about

  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  before_validation :generate_friendly_id, on: [:create, :update]

  def to_param
    friendly_id
  end

  private

  def generate_friendly_id
    self.friendly_id = PinYin.permlink(title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.limit(10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_friendly_id!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :content_html, :friendly_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; imtinge.top 2017</p>
            </div>
        </div>
    </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand csscf247d5c3195a6" href="/">就是在胡扯</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:imtinge@imtinge.top">Contact</a>
        </li>
        <li class="nav-item">
          <%= link_to 'New Post', new_post_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/common/_page_header.html.erb
<header class="masthead" >
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1 class="csscf247d5c3195a6">就是在胡扯</h1>
                    <img src="http://ovpkfkx95.bkt.clouddn.com/logo.jpg" width="150" height="150" alt="imtinge" class="img-thumbnail rounded-circle">
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="就是在胡扯">
    <meta name="author" content="imtinge">
    <title>就是在胡扯</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href='http://cdn.webfont.youziku.com/webfonts/nomal/103846/45807/59ad57b1f629d80bf07d57d8.css' rel='stylesheet' type='text/css' />
  </head>
  <body>
    <%= render 'common/navbar' %>
    <%= render 'common/page_header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'common/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/posts/_form.html.erb
<link href="https://cdn.bootcss.com/highlight.js/9.12.0/styles/github-gist.min.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/codemirror/5.29.0/codemirror.min.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/github-markdown-css/2.8.0/github-markdown.min.css" rel="stylesheet">
<style>
  .CodeMirror {
    height: 500px;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 0.25rem;
  }
  #preview_area {
    min-height: 300px;
    background:rgba(0, 0, 0, 0.15); 
    margin: 1rem;
  }
</style>
<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <label class="btn btn-default pull-right" onclick="preview_toggle()">Preview Toggle</label>
  <div class="row"></div>
  <div id="markdown_area">
    <%= f.input :content, label: false %>
  </div>
  <div style="display: none;">
    <%= f.input :content_html %>
  </div>
  <div id="preview_area" class="markdown-body">
  </div>
  <%= f.button :submit %>
<% end %>

<script src="https://cdn.bootcss.com/codemirror/5.29.0/codemirror.min.js"></script>
<script src="https://cdn.bootcss.com/codemirror/5.29.0/mode/markdown/markdown.min.js"></script>
<script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
<script>
  var editor
  
  var render_preview

  $(document).ready(function() {
    $("#preview_area").toggle()
    render_preview = function() { 
      var preview_html = marked(editor.getValue(), {
          sanitize: true,
          highlight: function(code) {
              return hljs.highlightAuto(code).value;
          }
      })
      $("#post_content_html").text(preview_html)
      $("#preview_area").html(preview_html)
    }

    editor = CodeMirror.fromTextArea(document.getElementById("post_content"), {
      mode: "markdown",
      tabSize: 2,
    });

    editor.on("change", render_preview)
  })

  function preview_toggle(){
    render_preview()
    $("#preview_area").toggle()
    $("#markdown_area").toggle()

  }

</script>

app/views/posts/_post.html.erb
<div class="post-preview">
  <%= link_to post do %>
  <h3 class="post-title">
    <%= post.title  %>
  </h3>
  <% end %>

  <p class="post-meta">
    <%= post.created_at %>
  </p>
</div>
<hr>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-lg-8 col-md-10 mx-auto">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<link href="https://cdn.bootcss.com/highlight.js/9.12.0/styles/github-gist.min.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/github-markdown-css/2.8.0/github-markdown.min.css" rel="stylesheet">
<style>
  	.markdown-body {
      box-sizing: border-box;
      min-width: 200px;
      max-width: 980px;
      margin: 0 auto;
      padding: 45px;
      border: 1px solid rgba(0, 0, 0, 0.15);
      border-radius: 0.25rem;
    }
</style>
<h2 class="post-title text-center">
  <%= @post.title  %>
</h2>
<p class="post-meta text-center">
  <%= @post.created_at %>
</p>
<div class="markdown-body">
  <%= sanitize @post.content_html %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>